// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhynXw2J0PIYdBrQFC54jGKPqfPZpDeVg',
    appId: '1:613700464106:web:90c56d1c8dc55c97af1693',
    messagingSenderId: '613700464106',
    projectId: 'codequestapp-23a98',
    authDomain: 'codequestapp-23a98.firebaseapp.com',
    storageBucket: 'codequestapp-23a98.firebasestorage.app',
    measurementId: 'G-2WRF94SYMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrVnYDbU8W7Xzc_L34WwqhNoQal4zGgE4',
    appId: '1:613700464106:android:e5b228743c6429e2af1693',
    messagingSenderId: '613700464106',
    projectId: 'codequestapp-23a98',
    storageBucket: 'codequestapp-23a98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtCRW-2ZmQjkt4yMwwix7-yIljdJsIXqI',
    appId: '1:613700464106:ios:7cac1d6b4a79e518af1693',
    messagingSenderId: '613700464106',
    projectId: 'codequestapp-23a98',
    storageBucket: 'codequestapp-23a98.firebasestorage.app',
    iosClientId: '613700464106-cvpe8c5adkg1k64u1lq6t4jm0hsinnsl.apps.googleusercontent.com',
    iosBundleId: 'com.example.codequestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtCRW-2ZmQjkt4yMwwix7-yIljdJsIXqI',
    appId: '1:613700464106:ios:7cac1d6b4a79e518af1693',
    messagingSenderId: '613700464106',
    projectId: 'codequestapp-23a98',
    storageBucket: 'codequestapp-23a98.firebasestorage.app',
    iosClientId: '613700464106-cvpe8c5adkg1k64u1lq6t4jm0hsinnsl.apps.googleusercontent.com',
    iosBundleId: 'com.example.codequestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhynXw2J0PIYdBrQFC54jGKPqfPZpDeVg',
    appId: '1:613700464106:web:a7343e68088e653daf1693',
    messagingSenderId: '613700464106',
    projectId: 'codequestapp-23a98',
    authDomain: 'codequestapp-23a98.firebaseapp.com',
    storageBucket: 'codequestapp-23a98.firebasestorage.app',
    measurementId: 'G-VX1LFBCHFR',
  );
}
